@startmul diagrama 

class Usuario
class Foco {
    - EstadoFoco estado 
    + Encender ()
    + Apagar ()
    + Estado ()
}
class EstadoFoco

Usuario o-- Foco
Foco *-- EstadoFoco
EstadoFoco --|> bool

@enduml